name: "Check for Missing Unit Tests"
description: "Checks if a PR introduces new functions without corresponding unit tests and adds comments to the PR."
author: "Moataz Nabil"
inputs:
  github-token:
    description: "GitHub token to authenticate API calls."
    required: true
runs:
  using: "node16"
  main: "scripts/check-missing-tests.js"
